name: CD

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21'

      - name: Install dependencies
        run: npm install

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Build and deploy
        run: npx vercel --token ${{ secrets.NEI }} --yes

  check_status:
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - name: Check Vercel Deployment status
        run: echo "Check Vercel status here"
        # Adicione comandos para verificar o status da implantação no Vercel
