name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Clear Node.js cache and install dependencies
      run: |
        rm -rf node_modules
        npm install

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 21

    - name: Install Dependencies
      run: npm install

    - name: Build Application
      run: npm run generate

    - name: Deploy to Vercel
      run: |
        npm install -g vercel
        vercel --token ${{ secrets.VERCEL_AUTH_TOKEN }}
