name: CD

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21'

      - name: Install dependencies
        run: yarn install

      - name: Build aplication
        run: yarn build

      - name: Deploy to GitHub Pages
        run:
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@users.noreply.github.com'
          git checkout --orphan gh-pages
          git --work-tree ./output add --all
          git --work-tree ./output commit -m "Deploying to GitHub Pages"
          git push origin HEAD:gh-pages --force